config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/resume' => 'welcome#resume'

  get '/projects' => 'projects#index'

  # STATIC PAGES
  get '/password_checker' => 'static_pages#password_checker'
  get '/jukebox2.0'       => 'static_pages#jukebox_2'
  get '/jukebox3.0'       => 'static_pages#jukebox_3'

  # BLOG
  # get '/blog'         => 'static_pages#blog'

  get '/allblogposts' => 'tagged_blogposts#index'

  # ================
  # PRODUCTION BLOG
  # ================
  
  resources :blogs

  # BLOG FILTERS
  get '/filter' => 'blogs#index'
  get '/filter/:tagid/:tagname'=> 'blogs#index'
  get '/filterbydate' =>'blogs#index'




end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :tagged_blogposts;
  has_many :tags, through: :tagged_blogposts;

  # override rails method for converting blog object to url param
  def to_param
    "#{id} #{title}".parameterize
  end

  def next
    Blog.where("id > ?", id).limit(1).first
  end

  def previous
    # Blog.where("id < ?", id).limit(1).first
    Blog.where("id < ?", id).last
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, uniqueness: true
  # join table
  has_many :tagged_blogposts
  #Tag.create(name:[string]).tagged_blogposts.blogs
  has_many :blogs, through: :tagged_blogposts
end

app/models/tagged_blogpost.rb
class TaggedBlogpost < ActiveRecord::Base
  belongs_to :blog
  belongs_to :tag
  # combination of blog id and tag id must be unique
  # one blog can be tagged with unique tag only once
  validates :blog_id, uniqueness: {scope: :tag_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate, :only => [:new, :edit]

  def index
    if params[:tagid].present?
      @blogs = Blog.joins(:tags).where("tags.id=?", "#{params[:tagid]}")
      @currentfilter = Tag.find(params[:tagid]);
    elsif params[:rubydate].present?
      logger.warn "THE RUBY DATE IS#{params[:rubydate]}"
      @blogs = Blog.all
    else
      @blogs = Blog.all
    end
  end

  def edit
    @blog = Blog.find(params[:id]);
  end

  def update
    @blog = Blog.find(params[:id]);
    if @blog.update(blog_params)
      redirect_to @blog
    else 
      flash.now[:error] = "coudlnt save"
      render action: "edit"    
    end
  end

  def show
    @blog=Blog.find(params[:id])
  end

  def new 
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
      if @blog.save
        redirect_to @blog
      else
        flash.now[:error] = "coudlnt save"
        render action: "new"
      end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body, :sub_heading, tag_ids: [])
  end

  def authenticate 
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BLOG_USERNAME"] && password == ENV["BLOG_PASSWORD"]
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout "static_pages"

  def password_checker
    # render layout: 'static_pages'
  end

  def jukebox_2
  end


  def jukebox_3
  end
end

app/controllers/tagged_blogposts_controller.rb
class TaggedBlogpostsController < ApplicationController

  layout "blog_tags"

  
  def index

    @taggedBlogPosts = TaggedBlogpost.all
    @tags = Tag.all


  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def resume
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
    markdown.render(content)
  end   
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tagged_blogposts_helper.rb
module TaggedBlogpostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_blogtagslist.html.erb
<span id="section-heading">
    <span>blog</span>
</span>

app/views/blogs/edit.html.erb
<%= form_for @blog, html: {class: "form-group"} do |b| %>
    
    <%= b.label :title %>
    <%= b.text_field :title, class: "form-control" %>

    <%= b.label :sub_heading %>
    <%= b.text_field :sub_heading, class: "form-control" %>

    <%= b.label :body %>
    <%= b.text_area :body, class: "form-control custom_form" %>

    <%= b.submit class: 'btn' %>

<% end %>

<style>
  body textarea.custom_form {
    height: 500px;
  }

</style>

app/views/blogs/index.html.erb
<div class="blog-header add-box-shadow">
  <%= render 'blogtagslist' %>
</div>

  <div class="allblogs">
    <!-- Show back button if filter applied -->
    <% if params[:tagid].present? %>

          <div class="back-nav">
            <div class="links">
              <div class="link">
                <div class="chevron left"></div>
                <%= link_to "Back to all blogs", blogs_path%>
              </div>
              <div class="link">
                <div class="chevron left"></div>
                <a href="/allblogposts" style="display:block">Blog Categories</a>
              </div>
            </div>
          </div>
        
    <% end %>
    <hr>
    <!-- all blogs -->
    <% @blogs.order("created_at DESC").each do |x| %>
      <%= link_to x, :style=>'text-decoration:none' do %>
          <div class="blog_main" style="margin-bottom:100px;">
              <div class="blogdate">
                <%#= x.created_at.strftime("%a, %B %d %Y") %>
                <%= x.created_at.strftime("%B %Y") %><hr>
              </div>
              <div class="headingandsubheading">
                <h1><%= x.title %></h1>
                <h4><%= x.sub_heading %></h4>
              </div>
              <div class="allblogtags">
                TAGS:<% x.tags.each do |x| %>
                      <%=link_to x.name, filter_path(tagid: x.id, tagname: x.name), class: 'blogtag' %>
                     <% end %> 
              </div>   
          </div>
      <% end %>
    <% end %>
  </div>
<!-- </div> -->

<!--  <div class="allblogs"> -->
    <!--   <%#@blogs.order("created_at DESC").each do |x|%>
        <%#=link_to x, :style=>'text-decoration:none' do%>
            <div id="blog">
             <!-- individual blogpost -->
                <!-- <div class="blog_main" style="margin-bottom:20px;"> -->
                  <%#=x.created_at.strftime("%a, %B %d %Y")%>
                  <!-- <div class="headingandsubheading"> -->
                    <!-- <h1 style="font-weight:100"><%#=x.title%></h1> -->
                    <!-- <h4 style="font-weight:100"><%#=x.sub_heading%></h4> -->
                  <!-- </div> -->
                <!-- </div> -->
        <%#end%>
        <!-- ending the link block (for post_path) before tag div -->
              <!-- <div class="blog_tags" style="margin-bottom:10px"> -->

                  <!-- tags for each individual post -->
                  <%#@blogs.tags.each do |x|%>

                  <%# if x.name === "Technical" %>
                      <!-- <i class="fa fa-cogs" style="color:#337ab7"> -->
                      <!-- <span style="font-family:Helvetica Neue, Helvetica, Arial, sans-serif"> -->
                      <%#=link_to x.name, filter_path(tagid: x.id)%>
                      <!-- </i><span style="font-family:Lato;color:black">  Technical</span> -->
                    <%# end %>
                    <!-- <span style="background-color:#CCE0ED;padding:2px 2px 2px 2px;color:gray;font-size:12px;margin:0px 5px 0px 0px;"> -->
                    <%#=link_to x.name, filter_path%>
                    <%#=link_to x.name, filter_path(tagid: x.id)%>
                    <!-- </span>        -->
                    
              <!-- </div>   -->

            <!-- </div> -->
            <%#end%>

           <!--   -->
            <!-- /individual blogpost -->
     <!--  <%#end%>
       <%#if params[:tagid].present?%>
          <span style="padding-bottom:30px;"><%#=link_to "Back", blogs_path%></span>
      <%#end%>
  </div>  -->
  <!-- /allblogs -->


<!--   <div class="blog-sidebar">

  </div>  -->





  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74494643-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/blogs/new.html.erb
<%= form_for @blog, html: {class: "form-group"} do |b| %>
    
    <%= b.label :title %>
    <%= b.text_field :title, class: "form-control" %>

    <%= b.label :sub_heading %>
    <%= b.text_field :sub_heading, class: "form-control" %>

    <%= b.label :body %>
    <%= b.text_area :body, class: "form-control custom_form" %>

    <%= b.label :tags %>
    <%= b.select :tag_ids, Tag.all.collect {|x| [x.name, x.id]}, {}, 
        :multiple => true %>

    <%=b.submit%>

<% end %>

<style>
  body textarea.custom_form {
    height: 500px;
  }

</style>

app/views/blogs/show.html.erb
<!-- BLOG SHOW PAGE -->

<div class="container"> 
<hr>

  <div class="col-sm-12">
      
      <!-- blog heading and subheading -->
      <div class="blogheading-showpage">
          <h1 style="letter-spacing:2px;font-size:50px;">
            <%=@blog.title%>
          </h1>
          <h5 style="word-spacing:3px;letter-spacing:1px;">
            <%= @blog.sub_heading %>
          </h5>
      </div>
  
      <!-- blog date -->
      <div class="blogdate-showpage">
          <% if @blog.updated_at.strftime("%a %B %d %Y") != @blog.created_at.strftime("%a %B %d %Y") %>
                This blog post was published in 
                  <span class="blogdate-showpage-actual-date">
                    <%= link_to @blog.created_at.strftime("%B %Y"), 
                        blogs_path(
                          filterbydate: @blog.created_at.strftime("%B%Y"),
                          rubydate: @blog.created_at
                        ); 
                    %>
                  </span>, 
                <span style="font-style:italic !important"> 
                and would later be edited in
                  <span class="blogdate-showpage-actual-date">
                    <%= link_to @blog.updated_at.strftime("%B %Y"), 
                        blogs_path(
                          filterbydate: @blog.updated_at.strftime("%B%Y"),
                          rubydate: @blog.updated_at
                        );
                    %>
                  </span>
              </span>
          <% else %>
              This blog post was published in 
                  <span class="blogdate-showpage-actual-date">
                    <%= link_to @blog.created_at.strftime("%B %Y"), 
                        blogs_path(
                          filterbydate: @blog.created_at.strftime("%B%Y"),
                          rubydate: @blog.created_at
                        );
                    %>
                  </span>
          <% end %>
      </div>


      <!-- blog tags -->
      <div>
        <span style="font-weight:100;text-transform:uppercase">
          Tagged Under: 
        </span>
        <% @blog.tags.each do |x| %>

          <span class="blogtag-show">
            <%= link_to x.name, filter_path(:tagid => x.id, :tagname=> x.name) %>
          </span>

        <% end %>
      </div>

      <hr>  
      
      <!-- blog body -->
      <div class="blog_post_body">
        <%=Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true).render(@blog.body).html_safe%>
      </div>


      <!-- Footer -->
      <span class="back-to-all-blogs">
        <%=link_to "Back to all blogs", blogs_path%>
      </span>

      <hr>
      
      <!-- Next and previous links -->
      <div class="next-and-prev-container">
        <div class="prev-container">
          <%if @blog.previous.present?%>
            <span class="button fa fa-angle-left"></span>
            <%=link_to @blog.previous do %>
              Previous Post<%#= @blog.previous.title %>
            <%end%>
          <%end%>
        </div>
        <div class="next-container">
          <%if @blog.next.present?%>
            <%=link_to @blog.next do %>
            Next Post
            <span class="button fa fa-angle-right"></span>
            <%#= @blog.next.title %>
            <%end%>
          <%end%>
        </div>
      </div>

      <!-- diquss comments -->
      <div id="disqus_thread"></div>
      <script type="text/javascript">
          /* * * CONFIGURATION VARIABLES * * */
          var disqus_shortname = 'i-fullstack';
          
          /* * * DON'T EDIT BELOW THIS LINE * * */
          (function() {
              var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
              dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
              (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

  </div>
  <!--/ col-sm-8 -->



<!-- <div class="col-sm-2">
</div> -->

</div>
<!-- /container -->



<!--  google analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74494643-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">

  <ul class="sidebar-list">
    <li>
      <a style="margin-left:0px;text-decoration:none;" href="/">Home</a>
    </li>
    <li>
      <a href="/blogs">Blog</a>
    </li>
    <li>
      <a href="/projects">Projects</a>
    </li>
  </ul>
  
</div>

    <!-- <li> <i class="fa fa-user fa-2x fa-fw aboutme"></i>About Me </li> -->
  <!-- <li> <i class="fa fa-laptop fa-2x fa-fw"></i>My Projects</li>  -->
  <!-- <li> <i class="fa fa-pencil fa-2x fa-fw"></i>Skills </li>  -->
<!-- <li><i class="fa fa-graduation-cap fa-2x fa-fw"></i>My Education</li> -->
<!-- <li><a href="/resume"><i class="fa fa-file fa-2x fa-fw"></i> </a> Resume</li> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tabish khan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
   <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
</head>
<body>

  <div id="sidebaricon">
    
    <span id="togglebutton">
      &#9776; MENU
    </span>

  </div>
    <!-- <div id="mycompany"> -->
    <span style="float:right;font-size:20px;font-weight:100;padding-top:10px;padding-right:10px;">
      iFullStack™
    </span>
    <!-- </div> -->
  
  

  <div class="wrapper">
    <%= yield %>
  </div>


  

<div class="sidebar">
<!-- <span class="close-sidebar">X</span> -->
<ul class="sidebar-list">
  <li>
    <a style="margin-left:0px;text-decoration:none;" href="/">
    Home
    </a>
  </li>
  <li>
    <a href="/blogs">
      Blog
    </a>
  </li>
  <li>
    <a href="/projects">
      Projects
    </a>
  </li>

  <!-- <li> <i class="fa fa-user fa-2x fa-fw aboutme"></i>About Me </li> -->
  <!-- <li> <i class="fa fa-laptop fa-2x fa-fw"></i>My Projects</li>  -->
  <!-- <li> <i class="fa fa-pencil fa-2x fa-fw"></i>Skills </li>  -->
<!-- <li><i class="fa fa-graduation-cap fa-2x fa-fw"></i>My Education</li> -->
<!-- <li><a href="/resume"><i class="fa fa-file fa-2x fa-fw"></i> </a> Resume</li> -->

</ul>

</div>
  
 
</body>




</html>

app/views/layouts/blog_tags.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>tabish khan</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
    <%=stylesheet_link_tag 'tagged_blogposts', media: 'all', 'data-turbolinks-track' => true%>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
   <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">
   <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
</head>
<body>

<!--   <div id="sidebaricon">
    
    <span id="togglebutton">
      &#9776; MENU
    </span>

  </div> -->
    <!-- <div id="mycompany"> -->
  <!--   <span style="float:right;font-size:20px;font-weight:100;padding-top:10px;padding-right:10px;">
      iFullStack™
    </span> -->
    <!-- </div> -->
  
  

  <div class="tagged_blogposts">
    <%= yield %>
  </div>


  
  <%= render 'layouts/sidebar' %>


</div>
  
 
</body>




</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
<head>
<%#= stylesheet_link_tag    'static_pages', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%=stylesheet_link_tag 'static_pages'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%=javascript_include_tag 'switch.js'%>

  <%=javascript_include_tag 'jaavz.js'%>
  <%=javascript_include_tag 'submitform.js'%>
  <%=javascript_include_tag 'howitworks.js'%>
</head>

<body>

  
  
    <%= yield %>


  
 
</body>




</html>

app/views/projects/_projects.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>1 Col Portfolio - Start Bootstrap Template</title>


    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/89f2f44ba07ea3fff7e561c2142813b278c2d6c6/devicon.min.css">


  

</head>

<body>

   
    <div class="container" id="projects">

       

        <!-- Project One -->
        <div class="row">
            <div class="col-md-7">
                <div class="projectimage">
                    
                    <%=image_tag 'codecorealumni', style: 'display:block;margin:auto;height:300px' %>
                <!-- <a href="#"> -->
                    <!-- <img class="img-responsive" src="http://placehold.it/700x300" alt=""> -->
                <!-- </a> -->
                </div>
            </div>
            <div class="col-md-5">
                <h3>CoreCore Alumni</h3>
                <h4>Site for you to connect with alumni from CodeCore Bootcamp</h4>
                <p>Ruby on Rails, Javascript, HML&CSS</p>
                <a class="btn btn-primary" href="https://code-core-alumini.herokuapp.com/">Live Demo <span class="glyphicon glyphicon-chevron-right"></span></a>
                <a class="btn btn-primary" href="https://github.com/tkhan003/CodeCore_alumni">Source Code <span class="glyphicon glyphicon-chevron-right"></span></a>
                    <br><br>

                 <span style="color:red"><i class="fa fa-signal fa-2x"></i>
                 In progress</span>

            </div>


        </div>

        <!-- /.row -->

        <hr>       
    </div>
  

app/views/projects/_projectstwo.html.erb
            <div class="container" id="projects">
<!-- /.row -->

        <!-- Project One -->
        <div class="row">
            <div class="col-md-7">
                <div class="projectimage">
                    
                    <img id="project_actual_image" style="height:300px;display:block;margin:auto;"class="img-responsive" src="
                    https://raw.githubusercontent.com/tkhan003/Password-Strength-Widget/master/password_strength.png" 
                    alt="password_strength">
                </div>
            </div>
            <div class="col-md-5">
                <h3>Password Stength Checker</h3>
                <h4>Javascript Widget</h4>
                <p>Checks the stength of your password. Styled using HTML&CSS. JQuery/Javascript used for making responsive.</p>
                <a class="btn btn-primary" href="http://i-full-stack.herokuapp.com//password_checker">Live Demo <span class="glyphicon glyphicon-chevron-right"></span></a>
                <a class="btn btn-primary" href="                https://github.com/tkhan003/Password-Strength-Widget
">Source Code <span class="glyphicon glyphicon-chevron-right"></span></a>
                
                <hr>
                <i style="font-size:20px;" class="devicon-javascript-plain" data-toggle="tooltip" data-placement="bottom" title="Javascript" ></i>&nbsp;
                <i style="font-size:20px;" class="devicon-bootstrap-plain" data-toggle="tooltip"  data-placement="bottom" title="Bootstrap" ></i>
                <!-- <i style="font-size:30px;color:#2E6DA4" class="devicon-html5-plain"></i> -->
                <!-- <i style="font-size:30px;color:#2E6DA4" class="devicon-css3-plain"></i> -->


            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Project Two -->
        <div class="row">
            <div class="col-md-7">
                <div>
                    <img class="img-responsive" src="https://raw.githubusercontent.com/tkhan003/chattr-js-chat-app/master/chattr-app.gif" alt="chattr" height="300" width="700">
                </div>
            </div>
            <div class="col-md-5">
                <h3>Chattr</h3>
                <h4>Chatting Application</h4>
                <p>Chat with your friends online! Development consisted of Ruby on Rails for backend and Javascript/jQuery for responsiveness and for AJAX purposes. </p>
                <a class="btn btn-primary" href="http://chattr-chatapp.herokuapp.com">Live Demo <span class="glyphicon glyphicon-chevron-right"></span></a>
                <a class="btn btn-primary" 
                href="https://github.com/tkhan003/chattr-js-chat-app">Source Code <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>
                <i style="font-size:20px;" class="devicon-javascript-plain" data-toggle="tooltip" data-placement="bottom" title="Javascript" ></i>&nbsp;
                <i style="font-size:20px;" class="devicon-rails-plain-wordmark" data-toggle="tooltip"  data-placement="bottom" title="Rails" ></i>
            </div>
        </div>
        <!-- /.row -->

        <!-- <hr> -->
       

        <hr>

    </div>

app/views/projects/index.html.erb
<div class="blog-header add-box-shadow">
  <span id="section-heading">
    projects
  </span>
</div>

  <div class="allblogs">
    <!-- Show back button if filter applied -->
   
  </div>
    <div id="mainproj_bottom">
        <div class="container">

        <div id="mainproj_div" style="height:200px;padding-top:70px;font-size:55px;font-weight:100">
            <span style="letter-spacing:5px;border:1px solid black;padding:10px 30px 10px 30px;">Projects
            <span style="font-weight:200;font-size:20px;color:gray">things i've made</span>
            </span>
            <!-- <span style="letter-spacing:5px;border:1px solid black;padding:10px 30px 10px 30px">Projects</span> -->
        </div>
    </div>
        <hr>


        <div id="projectsdiv">
            <%= render 'projects' %>
        </div>


    <div id="mainproj_bottom">
        <div class="container">

        <div id="mainproj_div" style="height:200px;padding-top:70px;font-size:55px;font-weight:100">
            <span style="letter-spacing:5px;border:1px solid black;padding:10px 30px 10px 30px;">Mini-Projects
            <span style="font-weight:200;font-size:20px;color:gray">some other things i've made</span>
            </span>
           
        </div>
    </div>
    
        <hr>

        <div>
            <%= render 'projectstwo' %>
        </div>


        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; iFullStack 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>





  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74494643-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/tagged_blogposts/index.html.erb
<div class="heading">Categories</div>

<div class="row">

  <div class="left-side">
      
      <!-- <div class="logo"></div> -->
      <img src="https://i.imgur.com/9QhMOGe.png" height="70%" width="70%">


  </div>

  <div class="tagged_blog_posts right-side">

    <ul class="tag_list">

      <% @tags.each do |tag| %>
        
        <li class="tag">

            <a href="/filter?tagid=<%=tag.id %>&tagname=<%=tag.name%>">
              <%= tag.name %>
              <span class="chevron right"></span>
            </a>

          </li>

      <% end %>
    </ul>

  </div>
</div>